name: bloc_dispose_scope
description: Package supporting bloc types for dispose_scope.
version: 3.0.0
repository: https://github.com/RobertOdrowaz/dispose-scope/tree/master/packages/bloc_dispose_scope
issue_tracker: https://github.com/RobertOdrowaz/dispose-scope/issues
homepage: https://github.com/RobertOdrowaz/dispose-scope

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^8.0.0
  dispose_scope: ^2.0.0
  meta: ^1.3.0

dev_dependencies:
  lint: ^1.5.3
  mocktail: ^0.3.0
  test: ^1.17.12
