name: dispose_scope
description: Package reducing boiler related to disposing/canceling/closing objects.
version: 1.0.0
repository: https://github.com/RobertOdrowaz/dispose-scope/tree/master/packages/dispose_scope
issue_tracker: https://github.com/RobertOdrowaz/dispose-scope/issues
homepage: https://github.com/RobertOdrowaz/dispose-scope

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.2.0
  leancode_lint: ^1.2.1
  mockito: ^5.0.8
  test: ^1.17.12
